mindmap
  root((pasar_fix))
    apps
      web
        src
          lib
            auth
            db
              schema
              migrations
            lingui
            orpc
            tanstack-query
          routes
            api
            auth
            admin
              stall
                -app
                -domain
                -components
            map
          components
            ui
          styles
          hooks
        public
          data
    data
    scripts
    docs
